base: core22
name: cross-autotools
version: '0.1'
summary: Autotools plugin example with cross-compile-utils
description: |
        Autotools plugin example with cross-compile-utils
grade: stable
confinement: strict

architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: [amd64, arm64]
    build-for: arm64
  - build-on: [amd64, armhf]
    build-for: armhf

apps:
  bash:
    command: bash
    plugs:
      - home

parts:
# HOST PARTS
  cross-build-utils.host:
    source: https://github.com/dbruno74/cross-build-utils.git
    plugin: nil
    override-pull: |
        craftctl default
        . $CRAFT_PART_SRC/install/cross-install

# TARGET PARTS
  bash:
    plugin: autotools
    source: http://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz
    autotools-configure-parameters: ["--infodir=/var/bash/info", "--host=$CRAFT_ARCH_TRIPLET"]
    organize:
      usr/local/bin/bash: bash
    override-build: |
      . ~/.cross-env
      prepare-gcc
      craftctl default
